### ISSUE TITLE
No whitespace when using '+' as a concatenation operator

### ISSUE THREAD

**Issue by boichee** [caarbon/node-conventions#5]
In some commentary on a PR in WiskeyTango/AtlasV2, @rawrin requested that I add whitespace when concatenating strings with the `+` operator.

See here: WiskeyTango/AtlasV2#6

For my part, I prefer to use different conventions depending upon how the `+` operator is being used so that's its easy to pick out the difference.

**So, when adding numbers:**

``` js
var x = 15 + 21;
```

**But when concatenating strings:**

``` js
var str1 = 'Concat me!'
var str2 = 'This is one string '+str1+' And I'm another.'
```

To me, the difference in whitespace makes it easy to see right away whether the operation is math or concatenation. I'd like to make this our convention if everyone is on board.

cc @tmarshall

**Comment by tmarshall** [comment]
interesting approach. I personally find that `'string a'+strb+'string c'` is harder to read when scanning files quickly, whereas `'string a' + strb + 'string c'` is clearer. Placement of `+` depending of the first var can become misleading if used incorrectly, or later changed.

For example, if you have:

``` js
function x(a, b) {
  return a+b;
}
```

then `x` is assumed to add strings, while

``` js
function y(a, b) {
  return a + b;
}
```

`y` is expected to add ints. Though if some data was set as `12` and `'7'` then `y` would actually return `'127'`.

Thoughts @rawrin?

**Comment by caamuerte** [comment]
@boichee :heart: :skull:

> I'm not afraid of death; I just don't want to be there when it happens.
> 
> _\- Woody Allen_
