### ISSUE TITLE
Deeply nested (3+ levels) synchronous function calls 

### ISSUE THREAD

**Issue by boichee** [caarbon/node-conventions#6]
Issue came up in ----- where a route had 3+ levels of nested control flow logic.

```
app.patch('/:id', selfWrap(
    preventIfCancelled(function(req, res) {
      require('./update')(req, res, Booking.patch);
    })
));
```

The suggested fix was to do something like this:

```
func1(
  func2(
    func3(
      func4(arg1, arg2)
    )
  }
);
```

More importantly, we basically agreed that in these cases if a function declaration is being passed as a callback, that function should also get its own vertical spacing and indentation. So the above example would become this:

```
func1(
  func2(
    func3(
      func4(arg1,
        function(req, res) {
           // stuff
        }
      )
    )
  )
);
```

**Comment by caamuerte** [comment]
@boichee :heart: :skull:

> Sleep, those little slices of death — how I loathe them.
> 
> _\- Edgar Allan Poe_
